# CLIP ViT-B/32 (OpenAI)
input_size: 224
backbone_name: clip_vitb32
flow_step: 8
hidden_ratio: 1.0
conv3x3_only: True
pooling_type: mean
gmm_n_components: 1
out_indices: [9, 10, 11]
preprocessing: none
