method: bayes
name: validation_threshold_dense121 #_w/augs
metric:
  name: best_accuracy
  goal: maximize

parameters:
  # Fixed parameters
  wandb:
    value: online
  data:
    value: FF4ALL
  reals:
    value: ffhq
  config:
    value: configs/densenet121.yaml
  model_type:
    value: FastFlow
  num_epochs:
    value: 1000
  eval_interval:
    value: 1
  early_stopping_patience:
    value: 50
  use_augs:
    value: 0
  
  # Hyperparameters to optimize
  optimizer:
    value: AdamW
  lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  
  weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-4
  
  batch_size:
    values:
      - 32
      - 64
      - 128

  scheduler:
    values:
      - 0
      - 1

  use_lof:
    values:
      - 0
      - 1
  
  lr_decay:
    distribution: uniform
    min: 0.1
    max: 0.9
  
  lr_patience:
    distribution: int_uniform
    min: 10
    max: 50
  
  # contamination:
  #   distribution: uniform
  #   min: 0.1
  #   max: 0.5

program: main.py
project: AD4DD